defaults: &defaults
  adapter: mysql
  username: root
  host: 127.0.0.1

development:
  <<: *defaults
  database: bikes_development

test:
  <<: *defaults
  database: bikes_test

production:
  <<: *defaults  
  database: bikes_production
